"""Backpopulates

Revision ID: 11de2f1242b6
Revises: f91416c33374
Create Date: 2021-11-11 00:28:02.385618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11de2f1242b6'
down_revision = 'f91416c33374'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
