"""Drop column type in users

Revision ID: 454645dfbb80
Revises: c9f67037d8d0
Create Date: 2021-11-12 19:51:54.856239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '454645dfbb80'
down_revision = 'c9f67037d8d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association',
    sa.Column('id_role', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_role'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id_role', 'id_user')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association')
    # ### end Alembic commands ###
