"""Hello World

Revision ID: f91416c33374
Revises: 
Create Date: 2021-11-11 00:13:24.122571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f91416c33374'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('activate', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('picture', sa.String(length=800), nullable=True),
    sa.Column('activate', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('picture', sa.String(length=800), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=True),
    sa.Column('cellphone', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('activate', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cellphone')
    )
    op.create_table('roles_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fk_role_roles_users', sa.Integer(), nullable=False),
    sa.Column('fk_user_roles_users', sa.Integer(), nullable=False),
    sa.Column('activate', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['fk_role_roles_users'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['fk_user_roles_users'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', 'fk_role_roles_users', 'fk_user_roles_users')
    )
    op.create_table('statistics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fk_users_statistics', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('activate', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['fk_users_statistics'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', 'fk_users_statistics')
    )
    op.create_table('teams_players',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fk_teams_teams_players', sa.Integer(), nullable=False),
    sa.Column('fk_users_teams_players', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('activate', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['fk_teams_teams_players'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['fk_users_teams_players'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', 'fk_teams_teams_players', 'fk_users_teams_players')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fk_teams_players_matches_one', sa.Integer(), nullable=False),
    sa.Column('fk_teams_players_matches_two', sa.Integer(), nullable=False),
    sa.Column('match_status_team_one', sa.String(length=25), nullable=True),
    sa.Column('match_status_team_two', sa.String(length=25), nullable=True),
    sa.Column('match_date', sa.DateTime(), nullable=True),
    sa.Column('activate', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['fk_teams_players_matches_one'], ['teams_players.id'], ),
    sa.ForeignKeyConstraint(['fk_teams_players_matches_two'], ['teams_players.id'], ),
    sa.PrimaryKeyConstraint('id', 'fk_teams_players_matches_one', 'fk_teams_players_matches_two')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    op.drop_table('teams_players')
    op.drop_table('statistics')
    op.drop_table('roles_users')
    op.drop_table('users')
    op.drop_table('teams')
    op.drop_table('roles')
    # ### end Alembic commands ###
